import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const GOOGLE_CLIENT_ID = Deno.env.get("GOOGLE_CLIENT_ID")!;
const GOOGLE_CLIENT_SECRET = Deno.env.get("GOOGLE_CLIENT_SECRET")!;

serve(async (req) => {
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  };
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { goalContent } = await req.json();
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // 1. DBからリフレッシュトークンを取得
    const { data: secretData, error: secretError } = await supabase
      .from('user_secrets')
      .select('google_refresh_token')
      .single(); // 仮に1ユーザーしかいない前提
    if (secretError || !secretData.google_refresh_token) throw new Error("Refresh token not found.");

    // 2. リフレッシュトークンを使って新しいアクセストークンを取得
    const tokenResponse = await fetch("https://oauth2.googleapis.com/token", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        client_id: GOOGLE_CLIENT_ID,
        client_secret: GOOGLE_CLIENT_SECRET,
        refresh_token: secretData.google_refresh_token,
        grant_type: "refresh_token",
      }),
    });
    const tokens = await tokenResponse.json();
    if (!tokens.access_token) throw new Error("Failed to refresh access token.");

    // 3. Googleカレンダーにイベントを作成
    const event = {
      'summary': goalContent,
      'description': 'Generated by My Growth Assistant',
      'start': {
        'date': new Date().toISOString().split('T')[0], // 今日の日付
      },
      'end': {
        'date': new Date().toISOString().split('T')[0], // 今日の日付
      },
    };

    const calendarResponse = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${tokens.access_token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(event),
    });

    if (!calendarResponse.ok) {
        const errorBody = await calendarResponse.json();
        throw new Error(`Failed to create calendar event: ${JSON.stringify(errorBody)}`);
    }

    return new Response(JSON.stringify({ message: "Calendar event created!" }), { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 200 });

  } catch (err) {
    return new Response(JSON.stringify({ message: err.message }), { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 });
  }
});
